
services:
  go-app:
    container_name: consultout-go-app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - go_redis

  go_db: 
    container_name: consultout-go-db
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  go_redis:
    container_name: consultout-go-redis
    image: redis:latest
    ports:
      - "6379:6379"

  go_worker:
    container_name: consultout-go-worker
    build: .
    command: ["./worker"]
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - go_redis

volumes:
  pgdata: {}
  db_data: {}
