
# main backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultout-backend
  labels:
    app: consultout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultout-backend
  template:
    metadata:
      labels:
        app: consultout-backend
    spec:
      containers:
      - name: consultout-backend
        image: nchiacedrick/my-app:e94a37794fdeaf51fdf4f60db91202f7b2b779ff
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: consultout-backend-secret




           