---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultout-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultout-redis
  template:
    metadata:
      labels:
        app: consultout-redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379

--- 
# PostgreSQL Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consultout-db
spec:
  serviceName: "consultout-db"
  replicas: 1
  selector:
    matchLabels:
      app: consultout-db
  template:
    metadata:
      labels:
        app: consultout-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: consultout-backend-config
        - secretRef:
            name: consultout-backend-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi  

---
# main backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultout-backend
  labels:
    app: consultout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultout-backend
  template:
    metadata:
      labels:
        app: consultout-backend
    spec:
      containers:
      - name: consultout-backend
        image: nchiacedrick/my-app:e13976ecc0cb33e96587c785a6f27fd72a20048c
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: consultout-backend-config
        - secretRef:
            name: consultout-backend-secret





