
# main backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultout-backend
  labels:
    app: consultout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultout-backend
  template:
    metadata:
      labels:
        app: consultout-backend
    spec:
      containers:
      - name: consultout-backend
        image: nchiacedrick/my-app:5f48190b7ea872191ebf2f3bd6492d83ca18a4d1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: consultout-backend-secret




           